### ISSUE TITLE
ban.js issue

### ISSUE THREAD

**Issue by flarely** [MaxThakurCodes/dbot-404#4]
Here's the direct error message copied from Terminal:
```
/dbot-404-master/config/config.json: Unexpected string in JSON at position 61
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1192:22)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/*/*/dbot-404-master/commands/ban.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
```

Thanks Max! 😃

**Comment by flarely** [comment]
idk if this is my problem! sorry if it's my problem :(

**Comment by MaxThakurCodes** [comment]
Hey, Ill check it out!
